version: '3.7'

services:
    mongodb:
        image: mongo:4.2.5
        container_name: mongo_caplc
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongocaplc
            MONGO_INITDB_ROOT_PASSWORD: mongocaplc
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        command: mongod --auth
