version: '3.7'

services:
    mongodb:
        image: mongo:4.2.5
        container_name: mongo_caplc
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:?err}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:?err}
        ports:
            - ${CAPLC_MONGODB_PORT:?err}:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        command: mongod --auth
